version: "3"
services:
  neo4j:
    container_name: neo4j
    image: neo4j:4.2.2
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
      - ./neo4j/conf:/conf
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_uuid_enabled=true
      - NEO4JLABS_PLUGINS=["apoc"]
    networks:
      - neo4j-net
    ports:
      - '7474:7474'
      - '7687:7687'
  app:
    container_name: goneo4jgql
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - neo4j-net
    ports:
      - '9090:9090'
    depends_on:
      - neo4j
    env_file:
      - .env


networks:
  neo4j-net:
    driver: 'bridge'